### ISSUE TITLE
您是否有意向对项目进行更换语言的重构

### ISSUE THREAD

**Issue by guobao2333** [A4-Tacks/mtsyntax-plus#1]
您的项目非常不错，我认为还算实用，但是为了编译mt语法高亮而需要额外安装 `rust` 环境，这可能并非一个好做法，您可以尝试使用 `GoLang` 或者 `JavaScript` 之类，更加常见的语言环境来重构项目。  
比如依附于 `JavaScript` 语言的 `nodejs` ，以及将程序编译为原生可执行文件的 `golang` 都是不错的选择！

当然，这仅仅只是我的一个建议，如果您愿意重构的话，我会很乐意帮您宣传您的项目，如果您没有时间或者不会这些语言的话也没关系……

我对您的项目非常感兴趣，因为这将会极大的提高我的开发速度。

最后，感谢您的伟大开源精神！

**Comment by A4-Tacks** [comment]
在这之前，我需要纠正一点：release 有静态原生可执行的编译成品，并不需要下载rust环境才可使用

JavaScript / TypeScript 的话会写但是并不方便，暂时没多少用它重构的意愿

**Comment by A4-Tacks** [comment]
这个问题是否已得到解决？如果已经解决或者没有回复，我将在稍后关闭它
